# Generated by Django 5.2 on 2025-05-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0002_metodopago_proveedor_pedido_producto_pedidoproducto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoProducto',
            new_name='DetallePedido',
        ),
    ]
