# Generated by Django 5.2 on 2025-04-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.AutoField(db_column='idPais', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=45, null=True)),
                ('Estado', models.CharField(db_column='Estado', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'Pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(db_column='idCiudad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45, null=True)),
                ('estado', models.CharField(db_column='estado', max_length=45, null=True)),
                ('Pais', models.ForeignKey(blank=True, db_column='Pais_idPais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='adminis.pais')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'Ciudad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idSede', models.AutoField(db_column='idSede', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45, null=True)),
                ('estado', models.CharField(db_column='estado', max_length=45, null=True)),
                ('Ciudad', models.ForeignKey(blank=True, db_column='Ciudad_idCiudad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='adminis.ciudad')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'Sede',
                'managed': True,
            },
        ),
    ]
