# Generated by Django 5.2 on 2025-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='estado',
            field=models.IntegerField(choices=[(0, 'inactivo'), (1, 'activo')], db_column='estado', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=100, null=True),
        ),
    ]
