# Generated by Django 5.2 on 2025-04-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminis', '0003_alter_sede_estado_alter_sede_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='Estado',
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='estado',
            field=models.IntegerField(choices=[(0, 'inactivo'), (1, 'activo')], db_column='estado', default=1, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='estado',
            field=models.IntegerField(choices=[(0, 'inactivo'), (1, 'activo')], db_column='estado', default=1, null=True),
        ),
    ]
