# Generated by Django 5.2 on 2025-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminis', '0004_remove_pais_estado_alter_ciudad_estado_pais_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='estado',
            field=models.BooleanField(choices=[(0, 'inactivo'), (1, 'activo')], db_column='estado', default=1, null=True),
        ),
    ]
