# Generated by Django 5.2 on 2025-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(choices=[(0, 'inactivo'), (1, 'activo')], default=0),
        ),
    ]
