# Generated by Django 5.2 on 2025-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_apellidos_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.IntegerField(choices=[(0, 'activo'), (1, 'inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'mesero'), (3, 'cajero')], default=3),
        ),
    ]
