# Generated by Django 5.2 on 2025-05-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminis', '0005_alter_sede_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la mesa')),
                ('capacidad', models.IntegerField(max_length=30, verbose_name='Capacidad de la mesa')),
                ('estado', models.BooleanField(choices=[(0, 'disponible'), (1, 'ocupado')], default=0, verbose_name='Estado de la mesa')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='adminis.sede', verbose_name='Sede asignada')),
            ],
        ),
    ]
