# Generated by Django 5.2 on 2025-05-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(verbose_name='Capacidad de la mesa'),
        ),
    ]
