# Generated by Django 5.2 on 2025-04-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='idCategoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='categoria',
            name='idcategoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
