# Generated by Django 5.2 on 2025-04-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_remove_categoria_idcategoria_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='idcategoria',
            new_name='idCategoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
