# Generated by Django 5.2 on 2025-04-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria2',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('idMesa', models.AutoField(primary_key=True, serialize=False)),
                ('numeroMesa', models.CharField(max_length=100)),
                ('Disponibilidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idMetodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveeedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('fhaPedido', models.DateTimeField()),
                ('totalPago', models.FloatField()),
                ('idMesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.mesa')),
                ('idMetodoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precioCompra', models.FloatField()),
                ('precioVenta', models.FloatField()),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.categoria2')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.mesa')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idMesa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('idCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='idSede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.sede'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='idSede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.sede'),
        ),
        migrations.CreateModel(
            name='Usuario2',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipoDocumento', models.CharField(max_length=5)),
                ('numDocumento', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.IntegerField()),
                ('estado', models.IntegerField(verbose_name='Estado')),
                ('idSede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.sede')),
            ],
        ),
    ]
