# Generated by Django 5.2 on 2025-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('pwd', models.TextField(verbose_name='Contraseña cifrada')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'mesero'), ('cajero', 'cajero')], max_length=6, verbose_name='Rol de usuario')),
            ],
        ),
    ]
